"""Fix foreign key name

Revision ID: 4488c24b9406
Revises: 
Create Date: 2025-03-17 22:14:07.523728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4488c24b9406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reply_to_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_foreign_key('fk_message_reply_to', 'message', ['reply_to_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
