"""Add failed_login_attempts and related fields to User

Revision ID: 66f30c34ba00
Revises: 301de5f29994
Create Date: 2025-03-18 00:31:02.011908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f30c34ba00'
down_revision = '301de5f29994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('last_failed_attempt')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
