name: Test and Notify and Auto-Merge

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
permissions:
  contents: write
  pull-requests: write

jobs:
  # =============================================
  # БЛОК ТЕСТИРОВАНИЯ
  # =============================================
  test-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Read version from file
      - name: Get version
        id: version
        run: |
          VERSION=$(cat version/version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::${VERSION}"

      # Настройка и тестирование фронтенда
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      # Запускаем Jest с выводом отчёта в JSON
      - name: Run Jest tests
        id: frontend-tests
        run: npx jest --json --outputFile=jest-results.json --verbose
        working-directory: ./frontend
        continue-on-error: true

      # Отправляем отдельное уведомление в Telegram для каждого теста
      - name: Send individual Telegram notifications for frontend tests
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -f jest-results.json ]; then
            cat jest-results.json | jq -c '.testResults[].assertionResults[]' | while read -r test; do
              TEST_NAME=$(echo "$test" | jq -r '.fullName')
              TEST_STATUS=$(echo "$test" | jq -r '.status')
              MESSAGE="Test: $TEST_NAME\nStatus: $TEST_STATUS"
              curl -s -X POST \
                https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
                -d chat_id=${TELEGRAM_CHAT_ID} \
                -d text="$(echo -e "$MESSAGE")" \
                -d parse_mode="HTML"
            done
          else
            echo "jest-results.json not found."
          fi
        working-directory: ./frontend
        shell: bash

      # Настройка и тестирование бэкенда
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest fastapi httpx
        working-directory: ./backend

      - name: Run backend tests
        id: backend-tests
        run: pytest -v
        working-directory: ./backend
        continue-on-error: true

      # Определяем общий статус тестирования и формируем итоговое сообщение
      - name: Determine test status
        id: test-status
        run: |
          FRONTEND_STATUS="${{ steps.frontend-tests.outcome }}"
          BACKEND_STATUS="${{ steps.backend-tests.outcome }}"
          
          if [[ "$FRONTEND_STATUS" == "success" && "$BACKEND_STATUS" == "success" ]]; then
            echo "MESSAGE=✅ All tests passed successfully!%0ABranch: ${{ github.ref_name }}%0ACommit: ${{ github.sha }}%0AVersion: ${{ env.VERSION }}" >> $GITHUB_ENV
            echo "STATUS=success" >> $GITHUB_ENV
          else
            echo "MESSAGE=❌ Some tests failed!%0ABranch: ${{ github.ref_name }}%0ACommit: ${{ github.sha }}%0AVersion: ${{ env.VERSION }}%0AFrontend: $FRONTEND_STATUS%0ABackend: $BACKEND_STATUS" >> $GITHUB_ENV
            echo "STATUS=failure" >> $GITHUB_ENV
          fi
        shell: bash

      # Отправляем итоговое уведомление в Telegram
      - name: Send Telegram final notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST \
            https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
            -d chat_id=${TELEGRAM_CHAT_ID} \
            -d text="$MESSAGE" \
            -d parse_mode="HTML"
        shell: bash

      # Отправляем итоговое уведомление по электронной почте
      - name: Send email with test results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SMTP_USER }}
          to: ${{ secrets.EMAIL_RECIPIENT }}
          subject: Test Results - ${{ github.ref_name }} (v${{ env.VERSION }})
          body: |
            The test results are as follows:
            ${{ env.MESSAGE }}
          secure: true

    outputs:
      test_status: ${{ env.STATUS }}
      version: ${{ env.VERSION }}

  sonar-analysis:
    needs: test-and-notify
    uses: ./.github/workflows/sonar-analysis.yml
    secrets: inherit

  #Куда девать этот блок?
  status:
    needs: test-and-notify
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test-and-notify.outputs.test_status }}" != "success" ]; then
            exit 1
          fi

  docker-push:
    needs: test-and-notify
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/messenger-backend:v${{ needs.test-and-notify.outputs.version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/messenger-backend:new
            ${{ secrets.DOCKER_HUB_USERNAME }}/messenger-backend:latest
          push: true

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/messenger-frontend:v${{ needs.test-and-notify.outputs.version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/messenger-frontend:new
            ${{ secrets.DOCKER_HUB_USERNAME }}/messenger-frontend:latest
          push: true

  # =============================================
  # БЛОК СОЗДАНИЯ PULL REQUEST (новый функционал)
  # =============================================

  create-pr:
    needs: test # Зависит от успешного тестирования
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Автоматическое создание PR с помощью популярного action
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Auto PR: ${{ github.ref_name }}" # Название PR
          body: "Automated PR from ${{ github.ref_name }}" # Описание
          base: develop # Целевая ветка (куда мержим)
          branch: "auto-pr/${{ github.ref_name }}" # Временная ветка
          delete-branch: true # Автоудаление временной ветки
          commit-message: "Automatic changes from ${{ github.ref_name }}"