name: Track Kanban Moves

on:
  project_card:
    types: [moved]

jobs:
  log_issue_move:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: read
    steps:
      - name: Extract issue info
        id: extract
        run: |
          CONTENT_URL="${{ github.event.project_card.content_url }}"
          ISSUE_NUMBER=$(echo $CONTENT_URL | awk -F/ '{print $NF}')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "Moved issue #$ISSUE_NUMBER to column ${{ github.event.project_card.column_url }}"

      - name: Get issue details
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.extract.outputs.ISSUE_NUMBER }};
            const response = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            console.log(`Issue Title: ${response.data.title}`);
            console.log(`URL: ${response.data.html_url}`);
