name: Project Card Reaction

on:
  project_card:
    types: [moved]

jobs:
  log-event:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      issues: read
      projects: read
      
    steps:
      - name: Log Event Data
        run: |
          echo "🔄 Карточка перемещена!"
          echo "Project ID: ${{ github.event.project_card.project_id }}"
          echo "Column ID: ${{ github.event.project_card.column_id }}"
          echo "Content URL: ${{ github.event.project_card.content_url }}"
          
          # Для отладки: полный JSON события
          echo "Full event data:"
          echo '${{ toJSON(github.event) }}' | jq .
