name: React to project item edit

on:
  projects_v2_item:
    types: [edited]

jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Элемент проекта отредактирован: ${{ github.event.projects_v2_item.id }}"
