name: Test Project Card Event

on:
  project_card:
    types: [created, moved]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        run: echo "${{ toJSON(github.event) }}"
