on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue number'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Process Issue
        run: |
          gh issue view ${{ inputs.issue-number }} --json title --jq '.title'
          # Дальнейшая логика...
