name: Deploy Docker Compose Project

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Make a test SSH connection with detailed debugging
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: 37.252.17.138
          username: nick
          key: ${{ secrets.DEPLOY_KEY }}
          port: 2222
          script: |
            echo "Connection successful"
            pwd
            whoami

      # Step 2: Copy files using scp-action
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: 37.252.17.138
          username: nick
          key: ${{ secrets.DEPLOY_KEY }}
          port: 2222
          source: "./"
          target: "/home/nick/project/"
          rm: false
          strip_components: 0
          overwrite: true
          timeout: 240s
          exclude: |
            .git/**
            .github/**
            node_modules/**

      # Step 3: Run Docker Compose commands
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 37.252.17.138
          username: nick
          key: ${{ secrets.DEPLOY_KEY }}
          port: 2222
          script: |
            cd /home/nick/project
            docker compose pull
            docker compose up -d --build
