name: Deploy to Minikube

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t project-frontend:latest ./frontend
          docker build -t project-backend:latest ./backend

      - name: Install Minikube and dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube config set driver docker
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Load images into Minikube
        run: |
          minikube image load project-frontend:latest
          minikube image load project-backend:latest

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f kubernetes-deployment.yaml
          kubectl rollout restart deployment/frontend
          kubectl rollout restart deployment/backend

      - name: Verify deployment
        run: |
          kubectl get pods -w &
          kubectl get services
          minikube service list
          kubectl rollout status deployment/frontend
          kubectl rollout status deployment/backend