name: Deploy Docker Compose Project

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          config: |
            Host deployment-server
              HostName 37.252.17.138
              User nick
              Port 2222
              StrictHostKeyChecking no

      - name: Debug connection
        run: |
          echo "Testing connection to server..."
          ssh -v deployment-server "echo Connection successful"
        continue-on-error: true

      - name: Copy project files to server
        run: |
          rsync -avz \
            --exclude='.git' --exclude='.github' --exclude='node_modules' \
            ./ deployment-server:/home/nick/project/
        shell: bash

      - name: Deploy via SSH
        run: |
          ssh deployment-server << 'EOF'
            cd /home/nick/project
            docker compose pull
            docker compose up -d --build
          EOF
        shell: bash
