name: Deploy to Kubernetes via SSH

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2222 37.252.17.138 >> ~/.ssh/known_hosts

      - name: Sync project files
        run: |
          rsync -avz -e "ssh -p 2222 -i ~/.ssh/deploy_key" \
            --exclude='.git' --exclude='.github' --exclude='node_modules' \
            ./ nick@37.252.17.138:/home/nick/project/

      - name: Build and deploy on remote
        run: |
          ssh -p 2222 -i ~/.ssh/deploy_key nick@37.252.17.138 << 'EOF'
            set -ex
            cd /home/nick/project
            
            # Сборка Docker образов
            docker build -t project-frontend:latest ./frontend
            docker build -t project-backend:latest ./backend
            
            # Загрузка образов в Minikube
            minikube image load project-frontend:latest
            minikube image load project-backend:latest
            
            # Применение Kubernetes конфигурации
            kubectl apply -f kubernetes-deployment.yaml
            
            # Рестарт деплоев для обновления
            kubectl rollout restart deployment/frontend
            kubectl rollout restart deployment/backend
            
            # Ожидание завершения
            kubectl rollout status deployment/frontend --timeout=3m
            kubectl rollout status deployment/backend --timeout=3m
          EOF