name: Deploy to Minikube

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2222 37.252.17.138 >> ~/.ssh/known_hosts

      - name: Sync project files
        run: |
          rsync -avz -e "ssh -p 2222 -i ~/.ssh/deploy_key" \
            --exclude='.git' --exclude='.github' --exclude='node_modules' \
            ./ nick@37.252.17.138:/home/nick/project/

      - name: Build and deploy on remote
        run: |
          ssh -p 2222 -i ~/.ssh/deploy_key nick@37.252.17.138 << 'EOF'
            set -ex
            cd /home/nick/project
            
            # Настройка Minikube
            minikube config set driver docker
            minikube start --cpus=4 --memory=8192 --disk-size=20g
            
            # Сборка образов внутри Minikube
            eval $(minikube -p minikube docker-env)
            docker build -t project-frontend:latest ./frontend
            docker build -t project-backend:latest ./backend
            
            # Применение конфигурации
            kubectl apply -f kubernetes-deployment.yaml
            
            # Перезапуск деплоев
            kubectl rollout restart deployment/frontend
            kubectl rollout restart deployment/backend
            
            # Ожидание обновления
            kubectl rollout status deployment/frontend --timeout=5m
            kubectl rollout status deployment/backend --timeout=5m
            
            # Проверка статуса
            kubectl get pods -o wide
            minikube service list
          EOF