name: Simple Push Example

on: [push] # Запускается при любом push в репозиторий

jobs:
  greeting:
    name: Print greeting
    runs-on: ubuntu-latest # ОС для выполнения задач
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Шаг 1: Получение кода из репозитория
        
      - name: Hello World
        run: echo "🎉 Новый код был запушен в репозиторий! 🚀"
