# .github/workflows/versioning.yml
name: Versioning and Changelog

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

env:
  VERSION_UP: '.github/scripts/version_up.py'
  NAME_VERSION_FILE: 'version/version'
  MAJOR: 'major'
  MINOR: 'minor'
  PATCH: 'patch'

jobs:
  versioning:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Get branch name
      - name: Extract branch name
        id: branch-names
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "current_branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # Update version for feature branches (minor)
      - name: Update version [minor]
        if: startsWith(steps.branch-names.outputs.current_branch, 'feature')
        run: |
          python ${{ env.VERSION_UP }} ${{ env.NAME_VERSION_FILE }} ${{ env.MINOR }}
          VERSION=$(cat ${{ env.NAME_VERSION_FILE }})
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      # Update version for hotfix branches (patch)
      - name: Update version [patch]
        if: startsWith(steps.branch-names.outputs.current_branch, 'hotfix')
        run: |
          python ${{ env.VERSION_UP }} ${{ env.NAME_VERSION_FILE }} ${{ env.PATCH }}
          VERSION=$(cat ${{ env.NAME_VERSION_FILE }})
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      # Get commit message
      - name: Get commit message
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      # Update changelog
      - name: Update Changelog
        if: env.NEW_VERSION != ''
        run: |
          TIMESTAMP=$(date '+%d.%m.%Y %H:%M:%S')
          CHANGELOG_FILE="CHANGELOG.md"
          
          # Create changelog if it doesn't exist
          if [ ! -f "$CHANGELOG_FILE" ]; then
            echo "# Changelog" > $CHANGELOG_FILE
            echo "" >> $CHANGELOG_FILE
          fi
          
          # Add new entry
          echo "## [${{ env.NEW_VERSION }}] - $TIMESTAMP" >> $CHANGELOG_FILE
          echo "" >> $CHANGELOG_FILE
          echo "- ${{ steps.commit.outputs.message }}" >> $CHANGELOG_FILE
          echo "" >> $CHANGELOG_FILE

      # Commit changes
      - name: Commit version and changelog
        if: env.NEW_VERSION != ''
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add ${{ env.NAME_VERSION_FILE }} version/version_log CHANGELOG.md
          git commit -m "Bump version to ${{ env.NEW_VERSION }} and update changelog"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}